let shopItemsData = [
  {
    id: "one",
    name: "Saree",
    desc: "A beautiful red Silk Saree",
    price: 1020,
    img: "images/Saree.jpg",
  },
  {
    id: "two",
    name: "Hoodie",
    desc: "A trendy Hoodie",
    price: 859,
    img: "images/Hoodie.jpg",
  },
  {
    id: "three",
    name: "Jeans",
    desc: "Set of cozy jean",
    price: 1150,
    img: "images/Jeans.jpg",
  },
  {
    id: "four",
    name: "Skirt",
    desc: "A modern skirt",
    price: 660,
    img: "images/skirt1.jpg",
  },
  {
    id: "five",
    name: "Crop-top",
    desc: "A simple crop-top",
    price: 455,
    img: "images/croptop.jpg",
  },
  {
    id: "six",
    name: "Slingbag",
    desc: "A Stylish Slingbag",
    price: 899,
    img: "images/Slingbag.jpg",
  },
  {
    id: "seven",
    name: "Heels",
    desc: "Elegant Heels",
    price: 999,
    img: "images/shoes.jpg",
  },
  {
    id: "eight",
    name: "Sport-shoes",
    desc: "A super-quality sportshoes",
    price: 2599,
    img: "images/sportsshoe.webp",
  },
];
